apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: forgerock-go-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: forgerock-go-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
